[package]
name = "zed-twig"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zed_extension_api = "0.7.0"

[lib]
crate-type = ["cdylib"]
