id = "smarty"
name = "Smarty"
version = "0.1.0"
schema_version = 1
authors = ["alsur"]
description = "Syntax highlighting and IntelliSense for Smarty templates in Zed"
repository = "https://github.com/alsur/zed-smarty"

[grammars.smarty]
repository = "https://github.com/alsur/tree-sitter-smarty"
commit = "8f066c7a24bced1a942cbdd88588cf75a5efda1e"

[language_servers.smarty-language-server]
name = "Smarty Language Server"
language = "Smarty"
