id = "smarty"
name = "Smarty"
version = "0.1.0"
schema_version = 1
authors = ["alsur"]
description = "Syntax highlighting and IntelliSense for Smarty templates in Zed"
repository = "https://github.com/alsur/zed-smarty"

[grammars.smarty]
repository = "https://github.com/alsur/tree-sitter-smarty"
commit = "d3e66413061437e59788ee9d3cd8f0376497bd38"

[language_servers.smarty-language-server]
name = "Smarty Language Server"
language = "Smarty"
